apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/argoapp-deployment.yaml
- manifests/argoapp-service.yaml
- manifests/ingress.yaml
- manifests/namespaces.yaml
images:
- name: PROJECT/ARGOAPP_IMAGE
  newName: ddeeh/argogitops
  newTag: d0f91222bc4d0dea5ba9b8283ec274407740ccb8
