apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argoapp
spec:
  destination:
    name: ''
    namespace: argoapp
    server: 'https://kubernetes.default.svc'
  source:
    path: .
    repoURL: 'https://github.com/andreedd/argogitops-app.git'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
