name: Release Argo Project

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ddeeh/argogitops:${{ github.sha }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v4

    - name: Set up Kustomize
      uses: imranismail/setup-kustomize@v2

    - name: Update yamls
      run: |
          kustomize edit set image PROJECT/PROJECT/ARGOAPP_IMAGE=ddeeh/argogitops:${{ github.sha }}
          git add .
          git commit -m "New version release for gitops-app `${GITHUB_SHA}`"
          git push
